### ISSUE TITLE
Elixir v1.0.5 and OTP 18.0

### ISSUE THREAD

**Issue by duijf** [danielberkompas/travis_elixir_plts#1]
Hi Daniel,

This seems really nice. We'd like to use the PLTs in this repository to test another project (for more details see mykewould/crutches#41).

The only issue are the newer versions of Elixir and OTP that aren't in this repository. If possible, we'd like to avoid doing duplicate work by generating and hosting these ourself when you are still interested in doing so. Are you still maintaining these?

Regards,
Laurens

**Comment by my-flow** [comment]
+1

**Comment by danielberkompas** [comment]
I will add the newer versions now. Thanks for the heads up! (Sorry it took so long, I need to do a better job of keeping up on my GitHub notifications)

**Comment by danielberkompas** [comment]
I ran [into some errors](https://travis-ci.org/danielberkompas/travis_elixir_plt_generator/jobs/78610457) generating PLTs with Erlang release 18. Don't have time to debug at the moment, but I was able to update the repo with Elixir version 1.0.5 built against releases <18.

**Comment by duijf** [comment]
It seems that Elixir does not yet support Erlang 18 fully (https://github.com/elixir-lang/elixir/issues/3212), and therefore Dialixir runs into some issues (https://github.com/jeremyjh/dialyxir/issues/26). This will sort itself out I guess.
