### ISSUE TITLE
Add PLTs for 1.4 RC1?

### ISSUE THREAD

**Issue by devonestes** [danielberkompas/travis_elixir_plts#3]
Hey @danielberkompas,

First off, thanks for maintaining this - makes Travis CI builds way faster and it's a huge help!!

I was wondering if you were planning on adding PLTs for the Elixir 1.4 release candidates, or if you'll wait for 1.4 to be released. I'm hoping to add the 1.4 RC1 to the build matrix for a couple projects so we can help debug 1.4 (and have more time to support that version).

Thanks again!

**Comment by danielberkompas** [comment]
Looking into it now. I'll try and get them up in the next couple of days.

**Comment by scmx** [comment]
This issue can probably be closed 🎉
